services:
  piltiservice:
    image: piltismartsolutions/piltiservices:v7.10.7
    container_name: piltiservices-test
    ports:
      - "9000:80"
    env_file:
      - ./.piltiservices.env
    volumes:
      - ./logs:/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/pilti/piltiUrls"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s
